# [Configuration file for NotifyUser by Nexamor]

notifications:
  sound-effect: CHICKEN_EGG_POP
  volume: 100
  pitch: 1
chat:
  symbol: '@'
  highlight-color: '&d'
  min-name-length: 3
  notify: true
