name: ${project.name}
author: Nexamor
main: com.minuxe.notifyuser.NotifyUser
version: ${project.version}
api-version: 1.13
description: ${project.description}
softdepend: [Factions]

commands:
   nu:
      description: Send a ping notification sound to a player.
      usage: '/nu [username|help|mute]'
      aliases: [notifyuser, nfy]
      permission: NotifyUser.player.send
      permission-message: You do not have permission to perform this command.

permissions:
   NotifyUser.*:
     description: Gives access to all NotifyUser commands.
     default: op
     children: 
       NotifyUser.player.*: true
       NotifyUser.admin.*: true
   NotifyUser.player.*: 
     description: Gives access to all standard player permissions.
     default: true
     children:
       NotifyUser.player.send: true
       NotifyUser.player.receive: true
       NotifyUser.player.mute: true
       NotifyUser.player.highlight: true
   NotifyUser.player.send:
     description: Allows a player to send in-chat and sound notifications.
     default: true
   NotifyUser.player.receive:
     description: Allows a player to receive in-chat and sound notifications.
     default: true
   NotifyUser.player.mute:
     description: Allows a player to mute any incoming notification sounds.
     default: true
   NotifyUser.player.highlight:
     description: Allows a player to see their name highlighted in chat when pinged.
     default: true
   NotifyUser.admin.*:
     description: Gives access to all admin permissions.
     children:
       NotifyUser.admin.set: true
       NotifyUser.admin.reload: true
     default: op
   NotifyUser.admin.set:
     description: Allows you to set the notification sound for all players.
     default: op
   NotifyUser.admin.reload:
     description: Allows you to use the reload command to update the config.
     default: op
   NotifyUser.override.*:
     description: Gives access to all overriding permissions.
     children:
       NotifyUser.override.notify: true
       NotifyUser.override.highlightall: true
     default: false
   NotifyUser.override.notify:
     description: Always receive silent notification alerts regardless of 'notify' option in config.
     default: false
   NotifyUser.override.highlightall:
     description: Always highlight all in-chat notifications regardless of 'highlight-all' option in config.
     default: false
   NotifyUser.anonymous.*:
     description: Gives access to all anonymous permissions.
     children:
       NotifyUser.anonymous.send: true
       NotifyUser.anonymous.receive: true
     default: false
   NotifyUser.anonymous.send:
     description: Always send silent notifications without revealing your username.
     default: false
   NotifyUser.anonymous.receive:
     description: Always see the username of anyone who sends you a silent notification (takes precedence over NotifyUser.anonymous.sender)
     default: false